/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
export type { AccessControl } from "./AccessControl";
export type { IAccessControl } from "./IAccessControl";
=======
>>>>>>> origin/develop
export type { Ownable } from "./Ownable";
