/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ListingContract {
  export type ListingParametersStruct = {
    assetContract: AddressLike;
    tokenId: BigNumberish;
    quantity: BigNumberish;
    currency: AddressLike;
    pricePerToken: BigNumberish;
    startTimestamp: BigNumberish;
    endTimestamp: BigNumberish;
    reserved: boolean;
  };

  export type ListingParametersStructOutput = [
    assetContract: string,
    tokenId: bigint,
    quantity: bigint,
    currency: string,
    pricePerToken: bigint,
    startTimestamp: bigint,
    endTimestamp: bigint,
    reserved: boolean
  ] & {
    assetContract: string;
    tokenId: bigint;
    quantity: bigint;
    currency: string;
    pricePerToken: bigint;
    startTimestamp: bigint;
    endTimestamp: bigint;
    reserved: boolean;
  };

  export type ListingStruct = {
    owner: AddressLike;
    assetContract: AddressLike;
    tokenId: BigNumberish;
    quantity: BigNumberish;
    currency: AddressLike;
    pricePerToken: BigNumberish;
    startTimestamp: BigNumberish;
    endTimestamp: BigNumberish;
    reserved: boolean;
    tokenType: BigNumberish;
    status: BigNumberish;
  };

  export type ListingStructOutput = [
    owner: string,
    assetContract: string,
    tokenId: bigint,
    quantity: bigint,
    currency: string,
    pricePerToken: bigint,
    startTimestamp: bigint,
    endTimestamp: bigint,
    reserved: boolean,
    tokenType: bigint,
    status: bigint
  ] & {
    owner: string;
    assetContract: string;
    tokenId: bigint;
    quantity: bigint;
    currency: string;
    pricePerToken: bigint;
    startTimestamp: bigint;
    endTimestamp: bigint;
    reserved: boolean;
    tokenType: bigint;
    status: bigint;
  };
}

export interface ListingContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveBuyerForListing"
      | "approveCurrencyForListing"
      | "buyFromListing"
      | "buyerApprovals"
      | "cancelListing"
      | "createListing"
      | "currencyApprovals"
      | "fee"
      | "getAllListings"
      | "getAllValidListings"
      | "getListing"
      | "getUserOwnedListings"
      | "listingCounter"
      | "listings"
      | "owner"
      | "renounceOwnership"
      | "setFee"
      | "totalListings"
      | "transferOwnership"
      | "updateListing"
      | "userOwnedListings"
      | "withdrawFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuyerApproved"
      | "CurrencyApproved"
      | "FeeWithdrawn"
      | "ListingCancelled"
      | "ListingCreated"
      | "ListingUpdated"
      | "NFTPurchased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveBuyerForListing",
    values: [BigNumberish, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "approveCurrencyForListing",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyFromListing",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerApprovals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createListing",
    values: [ListingContract.ListingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyApprovals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllListings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllValidListings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOwnedListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateListing",
    values: [BigNumberish, ListingContract.ListingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "userOwnedListings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveBuyerForListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveCurrencyForListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyFromListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllValidListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserOwnedListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userOwnedListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
}

export namespace BuyerApprovedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    isApproved: boolean
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    isApproved: boolean
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    isApproved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CurrencyApprovedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    currency: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    currency: string,
    price: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    currency: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeWithdrawnEvent {
  export type InputTuple = [admin: AddressLike, amount: BigNumberish];
  export type OutputTuple = [admin: string, amount: bigint];
  export interface OutputObject {
    admin: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCreatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    owner: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    owner: string,
    nftContract: string,
    tokenId: bigint,
    price: bigint,
    quantity: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    owner: string;
    nftContract: string;
    tokenId: bigint;
    price: bigint;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingUpdatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    newPrice: BigNumberish,
    newQuantity: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    newPrice: bigint,
    newQuantity: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    newPrice: bigint;
    newQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTPurchasedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    quantity: BigNumberish,
    totalPrice: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    quantity: bigint,
    totalPrice: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    quantity: bigint;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ListingContract extends BaseContract {
  connect(runner?: ContractRunner | null): ListingContract;
  waitForDeployment(): Promise<this>;

  interface: ListingContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveBuyerForListing: TypedContractMethod<
    [listingId: BigNumberish, buyer: AddressLike, toApprove: boolean],
    [void],
    "nonpayable"
  >;

  approveCurrencyForListing: TypedContractMethod<
    [
      listingId: BigNumberish,
      currency: AddressLike,
      pricePerTokenInCurrency: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  buyFromListing: TypedContractMethod<
    [
      listingId: BigNumberish,
      buyFor: AddressLike,
      quantity: BigNumberish,
      currency: AddressLike,
      expectedTotalPrice: BigNumberish
    ],
    [void],
    "payable"
  >;

  buyerApprovals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "payable"
  >;

  createListing: TypedContractMethod<
    [params: ListingContract.ListingParametersStruct],
    [bigint],
    "payable"
  >;

  currencyApprovals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  fee: TypedContractMethod<[], [bigint], "view">;

  getAllListings: TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ListingContract.ListingStructOutput[]],
    "view"
  >;

  getAllValidListings: TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ListingContract.ListingStructOutput[]],
    "view"
  >;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [ListingContract.ListingStructOutput],
    "view"
  >;

  getUserOwnedListings: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  listingCounter: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        assetContract: string;
        tokenId: bigint;
        quantity: bigint;
        currency: string;
        pricePerToken: bigint;
        startTimestamp: bigint;
        endTimestamp: bigint;
        reserved: boolean;
        tokenType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  totalListings: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateListing: TypedContractMethod<
    [listingId: BigNumberish, params: ListingContract.ListingParametersStruct],
    [void],
    "payable"
  >;

  userOwnedListings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawFee: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveBuyerForListing"
  ): TypedContractMethod<
    [listingId: BigNumberish, buyer: AddressLike, toApprove: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveCurrencyForListing"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      currency: AddressLike,
      pricePerTokenInCurrency: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyFromListing"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      buyFor: AddressLike,
      quantity: BigNumberish,
      currency: AddressLike,
      expectedTotalPrice: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "buyerApprovals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [params: ListingContract.ListingParametersStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "currencyApprovals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllListings"
  ): TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ListingContract.ListingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllValidListings"
  ): TypedContractMethod<
    [startId: BigNumberish, endId: BigNumberish],
    [ListingContract.ListingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [ListingContract.ListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOwnedListings"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "listingCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        owner: string;
        assetContract: string;
        tokenId: bigint;
        quantity: bigint;
        currency: string;
        pricePerToken: bigint;
        startTimestamp: bigint;
        endTimestamp: bigint;
        reserved: boolean;
        tokenType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalListings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateListing"
  ): TypedContractMethod<
    [listingId: BigNumberish, params: ListingContract.ListingParametersStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userOwnedListings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFee"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BuyerApproved"
  ): TypedContractEvent<
    BuyerApprovedEvent.InputTuple,
    BuyerApprovedEvent.OutputTuple,
    BuyerApprovedEvent.OutputObject
  >;
  getEvent(
    key: "CurrencyApproved"
  ): TypedContractEvent<
    CurrencyApprovedEvent.InputTuple,
    CurrencyApprovedEvent.OutputTuple,
    CurrencyApprovedEvent.OutputObject
  >;
  getEvent(
    key: "FeeWithdrawn"
  ): TypedContractEvent<
    FeeWithdrawnEvent.InputTuple,
    FeeWithdrawnEvent.OutputTuple,
    FeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ListingCreated"
  ): TypedContractEvent<
    ListingCreatedEvent.InputTuple,
    ListingCreatedEvent.OutputTuple,
    ListingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ListingUpdated"
  ): TypedContractEvent<
    ListingUpdatedEvent.InputTuple,
    ListingUpdatedEvent.OutputTuple,
    ListingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTPurchased"
  ): TypedContractEvent<
    NFTPurchasedEvent.InputTuple,
    NFTPurchasedEvent.OutputTuple,
    NFTPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BuyerApproved(uint256,address,bool)": TypedContractEvent<
      BuyerApprovedEvent.InputTuple,
      BuyerApprovedEvent.OutputTuple,
      BuyerApprovedEvent.OutputObject
    >;
    BuyerApproved: TypedContractEvent<
      BuyerApprovedEvent.InputTuple,
      BuyerApprovedEvent.OutputTuple,
      BuyerApprovedEvent.OutputObject
    >;

    "CurrencyApproved(uint256,address,uint256)": TypedContractEvent<
      CurrencyApprovedEvent.InputTuple,
      CurrencyApprovedEvent.OutputTuple,
      CurrencyApprovedEvent.OutputObject
    >;
    CurrencyApproved: TypedContractEvent<
      CurrencyApprovedEvent.InputTuple,
      CurrencyApprovedEvent.OutputTuple,
      CurrencyApprovedEvent.OutputObject
    >;

    "FeeWithdrawn(address,uint256)": TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;
    FeeWithdrawn: TypedContractEvent<
      FeeWithdrawnEvent.InputTuple,
      FeeWithdrawnEvent.OutputTuple,
      FeeWithdrawnEvent.OutputObject
    >;

    "ListingCancelled(uint256)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;

    "ListingCreated(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
    ListingCreated: TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;

    "ListingUpdated(uint256,uint256,uint256)": TypedContractEvent<
      ListingUpdatedEvent.InputTuple,
      ListingUpdatedEvent.OutputTuple,
      ListingUpdatedEvent.OutputObject
    >;
    ListingUpdated: TypedContractEvent<
      ListingUpdatedEvent.InputTuple,
      ListingUpdatedEvent.OutputTuple,
      ListingUpdatedEvent.OutputObject
    >;

    "NFTPurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      NFTPurchasedEvent.InputTuple,
      NFTPurchasedEvent.OutputTuple,
      NFTPurchasedEvent.OutputObject
    >;
    NFTPurchased: TypedContractEvent<
      NFTPurchasedEvent.InputTuple,
      NFTPurchasedEvent.OutputTuple,
      NFTPurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
