/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockReceiver,
  MockReceiverInterface,
} from "../../../src/Mock/MockReceiver";

const _abi = [
  {
    inputs: [],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
<<<<<<< HEAD
  "0x608060405234801561001057600080fd5b5061015a806100206000396000f3fe60806040526004361061001e5760003560e01c8063a6f2ae3a14610023575b600080fd5b61002b61002d565b005b61004167f329553ea0ef739960c01b6100a4565b6100556764d2565c04b6d81560c01b6100a4565b61006967422d2be852a620b960c01b6100a4565b6040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161009b90610104565b60405180910390fd5b50565b600082825260208201905092915050565b7f455448207472616e73666572206661696c656400000000000000000000000000600082015250565b60006100ee6013836100a7565b91506100f9826100b8565b602082019050919050565b6000602082019050818103600083015261011d816100e1565b905091905056fea2646970667358221220b82e5ed4ca7b57eba46b3f665b9ab635244145d86b501b7e8686de633e9e9bc564736f6c63430008180033";
=======
  "0x608060405234801561001057600080fd5b5061015a806100206000396000f3fe60806040526004361061001e5760003560e01c8063a6f2ae3a14610023575b600080fd5b61002b61002d565b005b61004167e0e6331d8fcf870360c01b6100a4565b610055672806ecfcb4550c4c60c01b6100a4565b6100696764159b058150e50c60c01b6100a4565b6040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161009b90610104565b60405180910390fd5b50565b600082825260208201905092915050565b7f455448207472616e73666572206661696c656400000000000000000000000000600082015250565b60006100ee6013836100a7565b91506100f9826100b8565b602082019050919050565b6000602082019050818103600083015261011d816100e1565b905091905056fea26469706673582212201eb49790e4481779f6e0b06cd270472a8a29331d8d987e3c5f14d855fda1422864736f6c63430008180033";
>>>>>>> origin/develop

type MockReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockReceiver__factory extends ContractFactory {
  constructor(...args: MockReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockReceiver__factory {
    return super.connect(runner) as MockReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockReceiverInterface {
    return new Interface(_abi) as MockReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockReceiver {
    return new Contract(address, _abi, runner) as unknown as MockReceiver;
  }
}
