/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PermissionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MANAGE_ASSET_ROLE"
      | "MANAGE_CURRENCY_ROLE"
      | "MANAGE_REQUESTS_ROLE"
      | "MANAGE_USER_ROLE"
      | "addCurrency"
      | "addUser"
      | "approveRequests"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "onlyWhitelistedNFT"
      | "onlyWhitelistedUser"
      | "pendingRequests"
      | "rejectRequests"
      | "removeCurrency"
      | "removeUser"
      | "removeWhitelistedNFT"
      | "renounceRole"
      | "requestNFTApproval"
      | "requestUserApproval"
      | "revokeRole"
      | "setOnlyWhitelistedNFT"
      | "setOnlyWhitelistedUser"
      | "supportedCurrencies"
      | "supportsInterface"
      | "validUsers"
      | "whitelistNFT"
      | "whitelistedNFTs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CurrencyAdded"
      | "CurrencyRemoved"
      | "NFTRemoved"
      | "NFTWhitelisted"
      | "RequestApproval"
      | "RequestApproved"
      | "RequestRejected"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UserAdded"
      | "UserRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGE_ASSET_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGE_CURRENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGE_REQUESTS_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGE_USER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCurrency",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRequests",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onlyWhitelistedNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onlyWhitelistedUser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRequests",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurrency",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhitelistedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestNFTApproval",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUserApproval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnlyWhitelistedNFT",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnlyWhitelistedUser",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedCurrencies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedNFTs",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGE_ASSET_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGE_CURRENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGE_REQUESTS_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGE_USER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onlyWhitelistedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyWhitelistedUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeWhitelistedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestNFTApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUserApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOnlyWhitelistedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOnlyWhitelistedUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedNFTs",
    data: BytesLike
  ): Result;
}

export namespace CurrencyAddedEvent {
  export type InputTuple = [currency: AddressLike];
  export type OutputTuple = [currency: string];
  export interface OutputObject {
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CurrencyRemovedEvent {
  export type InputTuple = [currency: AddressLike];
  export type OutputTuple = [currency: string];
  export interface OutputObject {
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRemovedEvent {
  export type InputTuple = [nft: AddressLike];
  export type OutputTuple = [nft: string];
  export interface OutputObject {
    nft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTWhitelistedEvent {
  export type InputTuple = [nft: AddressLike];
  export type OutputTuple = [nft: string];
  export interface OutputObject {
    nft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovalEvent {
  export type InputTuple = [target: AddressLike, requestType: BigNumberish];
  export type OutputTuple = [target: string, requestType: bigint];
  export interface OutputObject {
    target: string;
    requestType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [target: AddressLike, requestType: BigNumberish];
  export type OutputTuple = [target: string, requestType: bigint];
  export interface OutputObject {
    target: string;
    requestType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRejectedEvent {
  export type InputTuple = [target: AddressLike, requestType: BigNumberish];
  export type OutputTuple = [target: string, requestType: bigint];
  export interface OutputObject {
    target: string;
    requestType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAddedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRemovedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Permission extends BaseContract {
  connect(runner?: ContractRunner | null): Permission;
  waitForDeployment(): Promise<this>;

  interface: PermissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGE_ASSET_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGE_CURRENCY_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGE_REQUESTS_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGE_USER_ROLE: TypedContractMethod<[], [string], "view">;

  addCurrency: TypedContractMethod<
    [_currency: AddressLike],
    [void],
    "nonpayable"
  >;

  addUser: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  approveRequests: TypedContractMethod<
    [targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  onlyWhitelistedNFT: TypedContractMethod<[], [boolean], "view">;

  onlyWhitelistedUser: TypedContractMethod<[], [boolean], "view">;

  pendingRequests: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  rejectRequests: TypedContractMethod<
    [targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  removeCurrency: TypedContractMethod<
    [_currency: AddressLike],
    [void],
    "nonpayable"
  >;

  removeUser: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  removeWhitelistedNFT: TypedContractMethod<
    [_nft: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestNFTApproval: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestUserApproval: TypedContractMethod<[], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setOnlyWhitelistedNFT: TypedContractMethod<
    [_status: boolean],
    [void],
    "nonpayable"
  >;

  setOnlyWhitelistedUser: TypedContractMethod<
    [_status: boolean],
    [void],
    "nonpayable"
  >;

  supportedCurrencies: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  validUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistNFT: TypedContractMethod<[_nft: AddressLike], [void], "nonpayable">;

  whitelistedNFTs: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGE_ASSET_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGE_CURRENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGE_REQUESTS_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGE_USER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCurrency"
  ): TypedContractMethod<[_currency: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRequests"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "onlyWhitelistedNFT"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "onlyWhitelistedUser"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRequests"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rejectRequests"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeCurrency"
  ): TypedContractMethod<[_currency: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeWhitelistedNFT"
  ): TypedContractMethod<[_nft: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestNFTApproval"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUserApproval"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOnlyWhitelistedNFT"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOnlyWhitelistedUser"
  ): TypedContractMethod<[_status: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedCurrencies"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "validUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistNFT"
  ): TypedContractMethod<[_nft: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelistedNFTs"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "CurrencyAdded"
  ): TypedContractEvent<
    CurrencyAddedEvent.InputTuple,
    CurrencyAddedEvent.OutputTuple,
    CurrencyAddedEvent.OutputObject
  >;
  getEvent(
    key: "CurrencyRemoved"
  ): TypedContractEvent<
    CurrencyRemovedEvent.InputTuple,
    CurrencyRemovedEvent.OutputTuple,
    CurrencyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRemoved"
  ): TypedContractEvent<
    NFTRemovedEvent.InputTuple,
    NFTRemovedEvent.OutputTuple,
    NFTRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NFTWhitelisted"
  ): TypedContractEvent<
    NFTWhitelistedEvent.InputTuple,
    NFTWhitelistedEvent.OutputTuple,
    NFTWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproval"
  ): TypedContractEvent<
    RequestApprovalEvent.InputTuple,
    RequestApprovalEvent.OutputTuple,
    RequestApprovalEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRejected"
  ): TypedContractEvent<
    RequestRejectedEvent.InputTuple,
    RequestRejectedEvent.OutputTuple,
    RequestRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UserAdded"
  ): TypedContractEvent<
    UserAddedEvent.InputTuple,
    UserAddedEvent.OutputTuple,
    UserAddedEvent.OutputObject
  >;
  getEvent(
    key: "UserRemoved"
  ): TypedContractEvent<
    UserRemovedEvent.InputTuple,
    UserRemovedEvent.OutputTuple,
    UserRemovedEvent.OutputObject
  >;

  filters: {
    "CurrencyAdded(address)": TypedContractEvent<
      CurrencyAddedEvent.InputTuple,
      CurrencyAddedEvent.OutputTuple,
      CurrencyAddedEvent.OutputObject
    >;
    CurrencyAdded: TypedContractEvent<
      CurrencyAddedEvent.InputTuple,
      CurrencyAddedEvent.OutputTuple,
      CurrencyAddedEvent.OutputObject
    >;

    "CurrencyRemoved(address)": TypedContractEvent<
      CurrencyRemovedEvent.InputTuple,
      CurrencyRemovedEvent.OutputTuple,
      CurrencyRemovedEvent.OutputObject
    >;
    CurrencyRemoved: TypedContractEvent<
      CurrencyRemovedEvent.InputTuple,
      CurrencyRemovedEvent.OutputTuple,
      CurrencyRemovedEvent.OutputObject
    >;

    "NFTRemoved(address)": TypedContractEvent<
      NFTRemovedEvent.InputTuple,
      NFTRemovedEvent.OutputTuple,
      NFTRemovedEvent.OutputObject
    >;
    NFTRemoved: TypedContractEvent<
      NFTRemovedEvent.InputTuple,
      NFTRemovedEvent.OutputTuple,
      NFTRemovedEvent.OutputObject
    >;

    "NFTWhitelisted(address)": TypedContractEvent<
      NFTWhitelistedEvent.InputTuple,
      NFTWhitelistedEvent.OutputTuple,
      NFTWhitelistedEvent.OutputObject
    >;
    NFTWhitelisted: TypedContractEvent<
      NFTWhitelistedEvent.InputTuple,
      NFTWhitelistedEvent.OutputTuple,
      NFTWhitelistedEvent.OutputObject
    >;

    "RequestApproval(address,uint8)": TypedContractEvent<
      RequestApprovalEvent.InputTuple,
      RequestApprovalEvent.OutputTuple,
      RequestApprovalEvent.OutputObject
    >;
    RequestApproval: TypedContractEvent<
      RequestApprovalEvent.InputTuple,
      RequestApprovalEvent.OutputTuple,
      RequestApprovalEvent.OutputObject
    >;

    "RequestApproved(address,uint8)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestRejected(address,uint8)": TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;
    RequestRejected: TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UserAdded(address)": TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;
    UserAdded: TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;

    "UserRemoved(address)": TypedContractEvent<
      UserRemovedEvent.InputTuple,
      UserRemovedEvent.OutputTuple,
      UserRemovedEvent.OutputObject
    >;
    UserRemoved: TypedContractEvent<
      UserRemovedEvent.InputTuple,
      UserRemovedEvent.OutputTuple,
      UserRemovedEvent.OutputObject
    >;
  };
}
