/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPermissionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCurrency"
      | "assignAuctionRole"
      | "assignListingRole"
      | "assignNFTRole"
      | "assignOfferRole"
      | "hasRole"
      | "removeCurrency"
      | "requestNFTRole"
      | "requestUserRoles"
      | "revokeAuctionRole"
      | "revokeListingRole"
      | "revokeNFTRole"
      | "revokeOfferRole"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionRoleAssigned"
      | "AuctionRoleRevoked"
      | "CurrencyAdded"
      | "CurrencyRemoved"
      | "ListingRoleAssigned"
      | "ListingRoleRevoked"
      | "NFTRoleAssigned"
      | "NFTRoleRequested"
      | "NFTRoleRevoked"
      | "OfferRoleAssigned"
      | "OfferRoleRevoked"
      | "RoleRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCurrency",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assignAuctionRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assignListingRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assignNFTRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assignOfferRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurrency",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestNFTRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUserRoles",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuctionRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeListingRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeNFTRole",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOfferRole",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignAuctionRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignListingRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignNFTRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignOfferRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestNFTRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUserRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuctionRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeListingRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeNFTRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOfferRole",
    data: BytesLike
  ): Result;
}

export namespace AuctionRoleAssignedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionRoleRevokedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CurrencyAddedEvent {
  export type InputTuple = [currency: AddressLike];
  export type OutputTuple = [currency: string];
  export interface OutputObject {
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CurrencyRemovedEvent {
  export type InputTuple = [currency: AddressLike];
  export type OutputTuple = [currency: string];
  export interface OutputObject {
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingRoleAssignedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingRoleRevokedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRoleAssignedEvent {
  export type InputTuple = [nft: AddressLike];
  export type OutputTuple = [nft: string];
  export interface OutputObject {
    nft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRoleRequestedEvent {
  export type InputTuple = [
    nft: AddressLike,
    tokenId: BigNumberish,
    requester: AddressLike
  ];
  export type OutputTuple = [nft: string, tokenId: bigint, requester: string];
  export interface OutputObject {
    nft: string;
    tokenId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRoleRevokedEvent {
  export type InputTuple = [nft: AddressLike];
  export type OutputTuple = [nft: string];
  export interface OutputObject {
    nft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferRoleAssignedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferRoleRevokedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRequestedEvent {
  export type InputTuple = [requester: AddressLike, role: BytesLike];
  export type OutputTuple = [requester: string, role: string];
  export interface OutputObject {
    requester: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPermission extends BaseContract {
  connect(runner?: ContractRunner | null): IPermission;
  waitForDeployment(): Promise<this>;

  interface: IPermissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCurrency: TypedContractMethod<
    [_currencies: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assignAuctionRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assignListingRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assignNFTRole: TypedContractMethod<
    [_nfts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assignOfferRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  removeCurrency: TypedContractMethod<
    [_currencies: AddressLike[]],
    [void],
    "nonpayable"
  >;

  requestNFTRole: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestUserRoles: TypedContractMethod<
    [roles: BytesLike[]],
    [void],
    "nonpayable"
  >;

  revokeAuctionRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  revokeListingRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  revokeNFTRole: TypedContractMethod<
    [_nfts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  revokeOfferRole: TypedContractMethod<
    [_accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCurrency"
  ): TypedContractMethod<[_currencies: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignAuctionRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignListingRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignNFTRole"
  ): TypedContractMethod<[_nfts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignOfferRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeCurrency"
  ): TypedContractMethod<[_currencies: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestNFTRole"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUserRoles"
  ): TypedContractMethod<[roles: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAuctionRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeListingRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeNFTRole"
  ): TypedContractMethod<[_nfts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeOfferRole"
  ): TypedContractMethod<[_accounts: AddressLike[]], [void], "nonpayable">;

  getEvent(
    key: "AuctionRoleAssigned"
  ): TypedContractEvent<
    AuctionRoleAssignedEvent.InputTuple,
    AuctionRoleAssignedEvent.OutputTuple,
    AuctionRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionRoleRevoked"
  ): TypedContractEvent<
    AuctionRoleRevokedEvent.InputTuple,
    AuctionRoleRevokedEvent.OutputTuple,
    AuctionRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CurrencyAdded"
  ): TypedContractEvent<
    CurrencyAddedEvent.InputTuple,
    CurrencyAddedEvent.OutputTuple,
    CurrencyAddedEvent.OutputObject
  >;
  getEvent(
    key: "CurrencyRemoved"
  ): TypedContractEvent<
    CurrencyRemovedEvent.InputTuple,
    CurrencyRemovedEvent.OutputTuple,
    CurrencyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ListingRoleAssigned"
  ): TypedContractEvent<
    ListingRoleAssignedEvent.InputTuple,
    ListingRoleAssignedEvent.OutputTuple,
    ListingRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "ListingRoleRevoked"
  ): TypedContractEvent<
    ListingRoleRevokedEvent.InputTuple,
    ListingRoleRevokedEvent.OutputTuple,
    ListingRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRoleAssigned"
  ): TypedContractEvent<
    NFTRoleAssignedEvent.InputTuple,
    NFTRoleAssignedEvent.OutputTuple,
    NFTRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRoleRequested"
  ): TypedContractEvent<
    NFTRoleRequestedEvent.InputTuple,
    NFTRoleRequestedEvent.OutputTuple,
    NFTRoleRequestedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRoleRevoked"
  ): TypedContractEvent<
    NFTRoleRevokedEvent.InputTuple,
    NFTRoleRevokedEvent.OutputTuple,
    NFTRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OfferRoleAssigned"
  ): TypedContractEvent<
    OfferRoleAssignedEvent.InputTuple,
    OfferRoleAssignedEvent.OutputTuple,
    OfferRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "OfferRoleRevoked"
  ): TypedContractEvent<
    OfferRoleRevokedEvent.InputTuple,
    OfferRoleRevokedEvent.OutputTuple,
    OfferRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRequested"
  ): TypedContractEvent<
    RoleRequestedEvent.InputTuple,
    RoleRequestedEvent.OutputTuple,
    RoleRequestedEvent.OutputObject
  >;

  filters: {
    "AuctionRoleAssigned(address)": TypedContractEvent<
      AuctionRoleAssignedEvent.InputTuple,
      AuctionRoleAssignedEvent.OutputTuple,
      AuctionRoleAssignedEvent.OutputObject
    >;
    AuctionRoleAssigned: TypedContractEvent<
      AuctionRoleAssignedEvent.InputTuple,
      AuctionRoleAssignedEvent.OutputTuple,
      AuctionRoleAssignedEvent.OutputObject
    >;

    "AuctionRoleRevoked(address)": TypedContractEvent<
      AuctionRoleRevokedEvent.InputTuple,
      AuctionRoleRevokedEvent.OutputTuple,
      AuctionRoleRevokedEvent.OutputObject
    >;
    AuctionRoleRevoked: TypedContractEvent<
      AuctionRoleRevokedEvent.InputTuple,
      AuctionRoleRevokedEvent.OutputTuple,
      AuctionRoleRevokedEvent.OutputObject
    >;

    "CurrencyAdded(address)": TypedContractEvent<
      CurrencyAddedEvent.InputTuple,
      CurrencyAddedEvent.OutputTuple,
      CurrencyAddedEvent.OutputObject
    >;
    CurrencyAdded: TypedContractEvent<
      CurrencyAddedEvent.InputTuple,
      CurrencyAddedEvent.OutputTuple,
      CurrencyAddedEvent.OutputObject
    >;

    "CurrencyRemoved(address)": TypedContractEvent<
      CurrencyRemovedEvent.InputTuple,
      CurrencyRemovedEvent.OutputTuple,
      CurrencyRemovedEvent.OutputObject
    >;
    CurrencyRemoved: TypedContractEvent<
      CurrencyRemovedEvent.InputTuple,
      CurrencyRemovedEvent.OutputTuple,
      CurrencyRemovedEvent.OutputObject
    >;

    "ListingRoleAssigned(address)": TypedContractEvent<
      ListingRoleAssignedEvent.InputTuple,
      ListingRoleAssignedEvent.OutputTuple,
      ListingRoleAssignedEvent.OutputObject
    >;
    ListingRoleAssigned: TypedContractEvent<
      ListingRoleAssignedEvent.InputTuple,
      ListingRoleAssignedEvent.OutputTuple,
      ListingRoleAssignedEvent.OutputObject
    >;

    "ListingRoleRevoked(address)": TypedContractEvent<
      ListingRoleRevokedEvent.InputTuple,
      ListingRoleRevokedEvent.OutputTuple,
      ListingRoleRevokedEvent.OutputObject
    >;
    ListingRoleRevoked: TypedContractEvent<
      ListingRoleRevokedEvent.InputTuple,
      ListingRoleRevokedEvent.OutputTuple,
      ListingRoleRevokedEvent.OutputObject
    >;

    "NFTRoleAssigned(address)": TypedContractEvent<
      NFTRoleAssignedEvent.InputTuple,
      NFTRoleAssignedEvent.OutputTuple,
      NFTRoleAssignedEvent.OutputObject
    >;
    NFTRoleAssigned: TypedContractEvent<
      NFTRoleAssignedEvent.InputTuple,
      NFTRoleAssignedEvent.OutputTuple,
      NFTRoleAssignedEvent.OutputObject
    >;

    "NFTRoleRequested(address,uint256,address)": TypedContractEvent<
      NFTRoleRequestedEvent.InputTuple,
      NFTRoleRequestedEvent.OutputTuple,
      NFTRoleRequestedEvent.OutputObject
    >;
    NFTRoleRequested: TypedContractEvent<
      NFTRoleRequestedEvent.InputTuple,
      NFTRoleRequestedEvent.OutputTuple,
      NFTRoleRequestedEvent.OutputObject
    >;

    "NFTRoleRevoked(address)": TypedContractEvent<
      NFTRoleRevokedEvent.InputTuple,
      NFTRoleRevokedEvent.OutputTuple,
      NFTRoleRevokedEvent.OutputObject
    >;
    NFTRoleRevoked: TypedContractEvent<
      NFTRoleRevokedEvent.InputTuple,
      NFTRoleRevokedEvent.OutputTuple,
      NFTRoleRevokedEvent.OutputObject
    >;

    "OfferRoleAssigned(address)": TypedContractEvent<
      OfferRoleAssignedEvent.InputTuple,
      OfferRoleAssignedEvent.OutputTuple,
      OfferRoleAssignedEvent.OutputObject
    >;
    OfferRoleAssigned: TypedContractEvent<
      OfferRoleAssignedEvent.InputTuple,
      OfferRoleAssignedEvent.OutputTuple,
      OfferRoleAssignedEvent.OutputObject
    >;

    "OfferRoleRevoked(address)": TypedContractEvent<
      OfferRoleRevokedEvent.InputTuple,
      OfferRoleRevokedEvent.OutputTuple,
      OfferRoleRevokedEvent.OutputObject
    >;
    OfferRoleRevoked: TypedContractEvent<
      OfferRoleRevokedEvent.InputTuple,
      OfferRoleRevokedEvent.OutputTuple,
      OfferRoleRevokedEvent.OutputObject
    >;

    "RoleRequested(address,bytes32)": TypedContractEvent<
      RoleRequestedEvent.InputTuple,
      RoleRequestedEvent.OutputTuple,
      RoleRequestedEvent.OutputObject
    >;
    RoleRequested: TypedContractEvent<
      RoleRequestedEvent.InputTuple,
      RoleRequestedEvent.OutputTuple,
      RoleRequestedEvent.OutputObject
    >;
  };
}
