/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
import type * as iPermissionsSol from "./IPermissions.sol";
export type { iPermissionsSol };
import type * as mock from "./Mock";
export type { mock };
export type { Permissions } from "./Permissions";
=======
import type * as mock from "./Mock";
export type { mock };
export type { Listing } from "./Listing";
>>>>>>> origin/develop
