/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NFTAuction {
  export type AuctionStruct = {
    id: BigNumberish;
    auctionCreator: AddressLike;
    assetContract: AddressLike;
    tokenId: BigNumberish;
    startPrice: BigNumberish;
    ceilingPrice: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    timeBufferInSeconds: BigNumberish;
    highestBidder: AddressLike;
    highestBid: BigNumberish;
    stepAmount: BigNumberish;
    isPayoutCollected: boolean;
    isTokenCollected: boolean;
    status: BigNumberish;
    tokenType: BigNumberish;
  };

  export type AuctionStructOutput = [
    id: bigint,
    auctionCreator: string,
    assetContract: string,
    tokenId: bigint,
    startPrice: bigint,
    ceilingPrice: bigint,
    startTime: bigint,
    endTime: bigint,
    timeBufferInSeconds: bigint,
    highestBidder: string,
    highestBid: bigint,
    stepAmount: bigint,
    isPayoutCollected: boolean,
    isTokenCollected: boolean,
    status: bigint,
    tokenType: bigint
  ] & {
    id: bigint;
    auctionCreator: string;
    assetContract: string;
    tokenId: bigint;
    startPrice: bigint;
    ceilingPrice: bigint;
    startTime: bigint;
    endTime: bigint;
    timeBufferInSeconds: bigint;
    highestBidder: string;
    highestBid: bigint;
    stepAmount: bigint;
    isPayoutCollected: boolean;
    isTokenCollected: boolean;
    status: bigint;
    tokenType: bigint;
  };

  export type AuctionParamsStruct = {
    _assetContract: AddressLike;
    _tokenId: BigNumberish;
    _quantity: BigNumberish;
    _currency: AddressLike;
    _startPrice: BigNumberish;
    _ceilingPrice: BigNumberish;
    _stepAmount: BigNumberish;
    _timeBufferInSeconds: BigNumberish;
    _startTime: BigNumberish;
    _endTime: BigNumberish;
  };

  export type AuctionParamsStructOutput = [
    _assetContract: string,
    _tokenId: bigint,
    _quantity: bigint,
    _currency: string,
    _startPrice: bigint,
    _ceilingPrice: bigint,
    _stepAmount: bigint,
    _timeBufferInSeconds: bigint,
    _startTime: bigint,
    _endTime: bigint
  ] & {
    _assetContract: string;
    _tokenId: bigint;
    _quantity: bigint;
    _currency: string;
    _startPrice: bigint;
    _ceilingPrice: bigint;
    _stepAmount: bigint;
    _timeBufferInSeconds: bigint;
    _startTime: bigint;
    _endTime: bigint;
  };
}

export interface NFTAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bidInAuction"
      | "bids"
      | "cancelAuction"
      | "checkEnsureNFTBalance"
      | "collectAuctionPayout"
      | "collectAuctionToken"
      | "createAuction"
      | "getAllAuctions"
      | "getAllValidAuctions"
      | "getAuction"
      | "getNewWinningBid"
      | "isAuctionExpired"
      | "isNewWinningBid"
      | "onERC721Received"
      | "totalAuctions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCloser"
      | "AuctionPayoutCollected"
      | "AuctionTokenCollected"
      | "BidPlaced"
      | "CancelledAuction"
      | "NFTReceived"
      | "NewAuction"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bidInAuction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkEnsureNFTBalance",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectAuctionPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectAuctionToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [NFTAuction.AuctionParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAuctions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllValidAuctions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewWinningBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuctionExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isNewWinningBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAuctions",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bidInAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEnsureNFTBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectAuctionPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectAuctionToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllValidAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNewWinningBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuctionExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNewWinningBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAuctions",
    data: BytesLike
  ): Result;
}

export namespace AuctionCloserEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    assetContract: AddressLike,
    closer: AddressLike,
    tokenId: BigNumberish,
    auctionCreater: AddressLike,
    winningBidder: AddressLike
  ];
  export type OutputTuple = [
    auctionId: bigint,
    assetContract: string,
    closer: string,
    tokenId: bigint,
    auctionCreater: string,
    winningBidder: string
  ];
  export interface OutputObject {
    auctionId: bigint;
    assetContract: string;
    closer: string;
    tokenId: bigint;
    auctionCreater: string;
    winningBidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionPayoutCollectedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    auctionCreator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    auctionCreator: string,
    amount: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    auctionCreator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionTokenCollectedEvent {
  export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike];
  export type OutputTuple = [auctionId: bigint, bidder: string];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelledAuctionEvent {
  export type InputTuple = [
    auctionCreator: AddressLike,
    auctionId: BigNumberish
  ];
  export type OutputTuple = [auctionCreator: string, auctionId: bigint];
  export interface OutputObject {
    auctionCreator: string;
    auctionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTReceivedEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    tokenId: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    tokenId: bigint,
    data: string
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    tokenId: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewAuctionEvent {
  export type InputTuple = [
    auctionCreator: AddressLike,
    auctionId: BigNumberish,
    assetContract: AddressLike,
    auction: NFTAuction.AuctionStruct
  ];
  export type OutputTuple = [
    auctionCreator: string,
    auctionId: bigint,
    assetContract: string,
    auction: NFTAuction.AuctionStructOutput
  ];
  export interface OutputObject {
    auctionCreator: string;
    auctionId: bigint;
    assetContract: string;
    auction: NFTAuction.AuctionStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTAuction extends BaseContract {
  connect(runner?: ContractRunner | null): NFTAuction;
  waitForDeployment(): Promise<this>;

  interface: NFTAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bidInAuction: TypedContractMethod<
    [_auctionId: BigNumberish, _bidAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  bids: TypedContractMethod<
    [auctionId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  cancelAuction: TypedContractMethod<
    [_auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkEnsureNFTBalance: TypedContractMethod<
    [
      _assetContract: AddressLike,
      _tokenId: BigNumberish,
      _quantity: BigNumberish,
      types: BigNumberish
    ],
    [void],
    "view"
  >;

  collectAuctionPayout: TypedContractMethod<
    [_auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectAuctionToken: TypedContractMethod<
    [_auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAuction: TypedContractMethod<
    [_auctionParams: NFTAuction.AuctionParamsStruct],
    [void],
    "nonpayable"
  >;

  getAllAuctions: TypedContractMethod<
    [_startId: BigNumberish, _endId: BigNumberish],
    [NFTAuction.AuctionStructOutput[]],
    "view"
  >;

  getAllValidAuctions: TypedContractMethod<
    [_startId: BigNumberish, _endId: BigNumberish],
    [NFTAuction.AuctionStructOutput[]],
    "view"
  >;

  getAuction: TypedContractMethod<
    [_auctionId: BigNumberish],
    [NFTAuction.AuctionStructOutput],
    "view"
  >;

  getNewWinningBid: TypedContractMethod<
    [_auctionId: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  isAuctionExpired: TypedContractMethod<
    [_auctionId: BigNumberish],
    [boolean],
    "view"
  >;

  isNewWinningBid: TypedContractMethod<
    [_auctionId: BigNumberish, _bidAmount: BigNumberish],
    [boolean],
    "view"
  >;

  onERC721Received: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  totalAuctions: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bidInAuction"
  ): TypedContractMethod<
    [_auctionId: BigNumberish, _bidAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [auctionId: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[_auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkEnsureNFTBalance"
  ): TypedContractMethod<
    [
      _assetContract: AddressLike,
      _tokenId: BigNumberish,
      _quantity: BigNumberish,
      types: BigNumberish
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectAuctionPayout"
  ): TypedContractMethod<[_auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectAuctionToken"
  ): TypedContractMethod<[_auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [_auctionParams: NFTAuction.AuctionParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllAuctions"
  ): TypedContractMethod<
    [_startId: BigNumberish, _endId: BigNumberish],
    [NFTAuction.AuctionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllValidAuctions"
  ): TypedContractMethod<
    [_startId: BigNumberish, _endId: BigNumberish],
    [NFTAuction.AuctionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuction"
  ): TypedContractMethod<
    [_auctionId: BigNumberish],
    [NFTAuction.AuctionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNewWinningBid"
  ): TypedContractMethod<
    [_auctionId: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuctionExpired"
  ): TypedContractMethod<[_auctionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNewWinningBid"
  ): TypedContractMethod<
    [_auctionId: BigNumberish, _bidAmount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAuctions"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AuctionCloser"
  ): TypedContractEvent<
    AuctionCloserEvent.InputTuple,
    AuctionCloserEvent.OutputTuple,
    AuctionCloserEvent.OutputObject
  >;
  getEvent(
    key: "AuctionPayoutCollected"
  ): TypedContractEvent<
    AuctionPayoutCollectedEvent.InputTuple,
    AuctionPayoutCollectedEvent.OutputTuple,
    AuctionPayoutCollectedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionTokenCollected"
  ): TypedContractEvent<
    AuctionTokenCollectedEvent.InputTuple,
    AuctionTokenCollectedEvent.OutputTuple,
    AuctionTokenCollectedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "CancelledAuction"
  ): TypedContractEvent<
    CancelledAuctionEvent.InputTuple,
    CancelledAuctionEvent.OutputTuple,
    CancelledAuctionEvent.OutputObject
  >;
  getEvent(
    key: "NFTReceived"
  ): TypedContractEvent<
    NFTReceivedEvent.InputTuple,
    NFTReceivedEvent.OutputTuple,
    NFTReceivedEvent.OutputObject
  >;
  getEvent(
    key: "NewAuction"
  ): TypedContractEvent<
    NewAuctionEvent.InputTuple,
    NewAuctionEvent.OutputTuple,
    NewAuctionEvent.OutputObject
  >;

  filters: {
    "AuctionCloser(uint256,address,address,uint256,address,address)": TypedContractEvent<
      AuctionCloserEvent.InputTuple,
      AuctionCloserEvent.OutputTuple,
      AuctionCloserEvent.OutputObject
    >;
    AuctionCloser: TypedContractEvent<
      AuctionCloserEvent.InputTuple,
      AuctionCloserEvent.OutputTuple,
      AuctionCloserEvent.OutputObject
    >;

    "AuctionPayoutCollected(uint256,address,uint256)": TypedContractEvent<
      AuctionPayoutCollectedEvent.InputTuple,
      AuctionPayoutCollectedEvent.OutputTuple,
      AuctionPayoutCollectedEvent.OutputObject
    >;
    AuctionPayoutCollected: TypedContractEvent<
      AuctionPayoutCollectedEvent.InputTuple,
      AuctionPayoutCollectedEvent.OutputTuple,
      AuctionPayoutCollectedEvent.OutputObject
    >;

    "AuctionTokenCollected(uint256,address)": TypedContractEvent<
      AuctionTokenCollectedEvent.InputTuple,
      AuctionTokenCollectedEvent.OutputTuple,
      AuctionTokenCollectedEvent.OutputObject
    >;
    AuctionTokenCollected: TypedContractEvent<
      AuctionTokenCollectedEvent.InputTuple,
      AuctionTokenCollectedEvent.OutputTuple,
      AuctionTokenCollectedEvent.OutputObject
    >;

    "BidPlaced(uint256,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "CancelledAuction(address,uint256)": TypedContractEvent<
      CancelledAuctionEvent.InputTuple,
      CancelledAuctionEvent.OutputTuple,
      CancelledAuctionEvent.OutputObject
    >;
    CancelledAuction: TypedContractEvent<
      CancelledAuctionEvent.InputTuple,
      CancelledAuctionEvent.OutputTuple,
      CancelledAuctionEvent.OutputObject
    >;

    "NFTReceived(address,address,uint256,bytes)": TypedContractEvent<
      NFTReceivedEvent.InputTuple,
      NFTReceivedEvent.OutputTuple,
      NFTReceivedEvent.OutputObject
    >;
    NFTReceived: TypedContractEvent<
      NFTReceivedEvent.InputTuple,
      NFTReceivedEvent.OutputTuple,
      NFTReceivedEvent.OutputObject
    >;

    "NewAuction(address,uint256,address,tuple)": TypedContractEvent<
      NewAuctionEvent.InputTuple,
      NewAuctionEvent.OutputTuple,
      NewAuctionEvent.OutputObject
    >;
    NewAuction: TypedContractEvent<
      NewAuctionEvent.InputTuple,
      NewAuctionEvent.OutputTuple,
      NewAuctionEvent.OutputObject
    >;
  };
}
