/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iPermissionsSol from "./IPermissions.sol";
export * as mock from "./Mock";
export { Permissions__factory } from "./Permissions__factory";
